services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8085:80'
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: pokedex
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: