services:
  frontend:
    image: frontend:local
    build:
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: http://localhost:8181
    ports:
      - '8085:8080'
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
  backend:
    volumes:
      - ./backend:/app
    image: backend:local
    build:
      dockerfile: Dockerfile.backend
    ports:
      - '8181:8181'
      - '5680:5678'
    command:
      python -m debugpy --listen 0.0.0.0:5678 -m flask run --host=0.0.0.0 --port=8181
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./main.py
      DATABASE_URL: postgresql://ash:dbpassword@db/pokedex
    depends_on:
      - db
  db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_DB: pokedex
      POSTGRES_USER: ash
      POSTGRES_PASSWORD: dbpassword
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./resources/database_backup.sql:/docker-entrypoint-initdb.d/database_backup.sql

volumes:
  postgres_data: