FROM node:20.12.2-alpine as build

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install -g pnpm && pnpm install

COPY frontend/ .

RUN pnpm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]