FROM python:3.12-slim

ENV PYTHONUNBUFFERED True

RUN apt-get update && apt-get install -y

WORKDIR /app

COPY backend/ .

RUN pip install --no-cache-dir -r requirements.txt

CMD exec gunicorn --bind :8181 --workers 1 --threads 8 --timeout 0 main:app